version: '3.8'
services:
  app:
    image: "ghcr.io/chaewonkong/msa-link-api:v0.1.4"
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_NAME=linkdb
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - DB_TIMEZONE=Asia/Seoul
      - QUEUE_HOST=queue
      - QUEUE_USER=admin
      - QUEUE_PASSWORD=1234
      - QUEUE_PORT=5672
    depends_on:
      - db
      - queue
    restart: always
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=linkdb
      - POSTGRES_PORT=5432
    volumes:
      - ./data:/var/lib/postgresql/data
  queue:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "1234"
    ports:
      - "5672:5672"
      - "15672:15672"
  scraper:
    image: "ghcr.io/chaewonkong/msa-link-scraper:v0.1.0"
    environment:
      - QUEUE_HOST=queue
      - QUEUE_USER=admin
      - QUEUE_PASSWORD=1234
      - QUEUE_PORT=5672
      - API_HOST=http://app:8080
      - QUEUE_NAME=link_queue
    depends_on:
      - queue
      - app
    restart: always